kakao:
  client:
    clientId:
    accessTokenUri: https://kauth.kakao.com/oauth/token
    userAuthorizationUri: https://kauth.kakao.com/oauth/authorize
  resource:
    userInfoUri: https://kauth.kakao.com/v2/user/me


spring:
  data:
    rest:
      base-path: /api
      default-page-size: 10
      max-page-size: 10
